services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend1:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: movies_db
    ports:
      - "8080:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app

  backend2:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: movies_db
    ports:
      - "8081:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app


  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  postgres_data:
