version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Instalar Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version

      - run:
          name: Construir y levantar servicios
          command: docker-compose up -d --build

      - run:
          name: Esperar servicios
          command: sleep 15

      - run:
          name: Ejecutar pruebas API
          command: |
            pip install -r backend/app/requirements.txt
            pytest backend/app/test_main.py

      - run:
          name: Apagar servicios
          command: docker-compose down

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
